apiVersion: v1
kind: ConfigMap
metadata:
  name: potpie-config
  namespace: default
data:
  PORT: "8080"
  REDIS_HOST: "valkey.valkey.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_TLS_ENABLED: "false"
  REDIS_TLS_REJECT_UNAUTHORIZED: "false"
  MAX_CONCURRENT_JOBS: "5"
  MAX_RETRIES: "3"
  QUEUE_NAME: "potpie-analysis"
  LOG_LEVEL: "info"
  REQUEST_TIMEOUT: "30000"
  CUSTOM_AGENT_ID: "fe5f00ae-6737-4953-8fb6-8b71153da4eb"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: potpie-service
  namespace: default
  labels:
    app: potpie-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: potpie-service
  template:
    metadata:
      labels:
        app: potpie-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: potpie-service
          image: pagewings/coderide-potpie-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: POTPIE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: potpie-secrets
                  key: POTPIE_API_KEY
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: potpie-secrets
                  key: REDIS_PASSWORD
          envFrom:
            - configMapRef:
                name: potpie-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: potpie-service-monitor
  namespace: default
  labels:
    app: potpie-service
spec:
  selector:
    matchLabels:
      app: potpie-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
