apiVersion: v1
kind: Secret
metadata:
  name: potpie-secrets
  namespace: default
type: Opaque
stringData:
  POTPIE_API_KEY: "la_tua_chiave_potpie_api"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: potpie-service
  namespace: default
  labels:
    app: potpie-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: potpie-service
  template:
    metadata:
      labels:
        app: potpie-service
        version: v1
    spec:
      containers:
      - name: potpie-service
        image: coderide-potpie-service:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: POTPIE_API_KEY
          valueFrom:
            secretKeyRef:
              name: potpie-secrets
              key: POTPIE_API_KEY
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
