apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: valkey
  labels:
    app: valkey
spec:
  selector:
    app: valkey
  ports:
  - name: valkey-tls
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
